### ISSUE TITLE
Update Elasticsearch version 1.7.1

### ISSUE THREAD

**Issue by chhantyal** [f500/ansible-elasticsearch#10]
Looks like latest stable version is 1.7.1.

I am trying to use Elasticsearch for Graylog (https://www.graylog.org) 
Graylog doesn't work with ES =< 1.6

**Comment by ramondelafuente** [comment]
We haven't changed the default version due to keeping backward compatibility. But it seems 1.5 is really outdated now so we'll change the default soon. However, the Elasticsearch version is a variable that you can set `elasticsearch_version=1.7`.

In the meantime, check out this role from Greylog (they use this very role as a dependency) 

https://github.com/graylog2/graylog-ansible-role

**Comment by ramondelafuente** [comment]
It's in galaxy even: https://galaxy.ansible.com/list#/roles/3162

**Comment by chhantyal** [comment]
@ramondelafuente Thanks for the tip, I will change variable. 

Yes, Graylog-ansible-role uses this as dependency, and it doesn't work. 

They updated readme to use 1.7 https://github.com/Graylog2/graylog-ansible-role/commit/b3175968ccf69b985ae9fff53a31a63626650012

**Comment by ramondelafuente** [comment]
Ah yes, I see. We'll update it to 1.7 asap :-)

**Comment by ramondelafuente** [comment]
Default version of ES changed to 1.7 (role tagged v3.0.0)
